import type { Config } from 'tailwindcss';

const config: Config = {
    darkMode: 'class',
    content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
    theme: {
        extend: {
            colors: {
                primary: {
                    100: '#D6F0FF',
                    300: '#8EC9FF',
                    default: '#2E89FF ',
                    700: '#1454E1',
                    900: '#193E8E',
                },
                extendedNeutral: {
                    100: '#E1E1E1',
                    300: '#9D9D9D',
                    DEFAULT: '#5A5958',
                    600: '#3F3D3C',
                    900: '#1D1B1A',
                },
                extendedRed: {
                    100: '#FCC2CF',
                    300: '#F85F82',
                    DEFAULT: '#F40139',
                    700: '#AD0128',
                    900: '#6E001E',
                },
                extendedOrange: {
                    100: '#FFF2D4',
                    300: '#FFDC8E',
                    DEFAULT: '#FFC84C',
                    700: '#B58E36',
                    900: '#735A22',
                },
                secondary: {},
                error: {
                    lighter: 'red[300]',
                    light: 'red[500]',
                    DEFAULT: 'red[600]',
                    dark: 'red[700]',
                    darker: 'red[900]',
                    contrastText: '#fff',
                },
                warning: {
                    lighter: 'yellow[300]',
                    light: 'yellow[500]',
                    DEFAULT: 'yellow[600]',
                    dark: 'yellow[700]',
                    darker: 'yellow[900]',
                    contrastText: 'gray[100]',
                },
                info: {
                    lighter: 'cyan[300]',
                    light: 'cyan[500]',
                    DEFAULT: 'cyan[600]',
                    dark: 'cyan[700]',
                    darker: 'cyan[900]',
                    contrastText: '#fff',
                },
                success: {
                    lighter: 'green[300]',
                    light: 'green[500]',
                    DEFAULT: 'green[600]',
                    dark: 'green[700]',
                    darker: 'green[900]',
                    contrastText: '#fff',
                },
                bgTextfield: '#F8F9FA',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                chart: {
                    '1': 'hsl(var(--chart-1))',
                    '2': 'hsl(var(--chart-2))',
                    '3': 'hsl(var(--chart-3))',
                    '4': 'hsl(var(--chart-4))',
                    '5': 'hsl(var(--chart-5))',
                },
            },
        },
        screens: {
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
            '2xl': '1536px',
        },
        spacing: {
            xs: '8px',
            sm: '12px',
            md: '16px',
            lg: '48px',
            xl: '56px',
            '2xl': '64px',
            '3xl': '80px',
            '4xl': '96px',
        },
        Typography: {
            'text-xs': '12px',
            'text-sm': '14px',
            'text-md': '16px',
            'text-lg': '18px',
            'text-xl': '20px',
            'text-2xl': '24px',
            'text-3xl': '30px',
            'text-4xl': '36',
        },
    },
    plugins: [require('tailwindcss-animate')],
};
export default config;
